### ISSUE TITLE
Mismatch of Firefox & Geckodriver versions?

### ISSUE THREAD

**Issue by XtremePwnership** [pyronlaboratory/heroku-integrated-firefox-geckodriver#10]
Hi, i added this buildpack to heroku but keep getting this error:

`selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process `

After searching about it, it seems this is caused by incompatible Firefox & Geckodriver versions. Any help on how to solve this error? Thank you.

**Comment by XtremePwnership** [comment]
I keep getting this error when trying to create the Selenium Webdriver object:

` File "sendSWA.py", line 29, in sendScheduledMessage                                                                       driver = webdriver.Firefox(firefox_profile=fp, options=options, executable_path=os.environ.get("GECKODRIVER_PATH"),firefox_binary=os.environ.get("FIREFOX_BIN"))                                                                              File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__     keep_alive=True)                                                                                                      File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__      self.start_session(capabilities, browser_profile)                                                                     File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session                                                                                                                         response = self.execute(Command.NEW_SESSION, parameters)                                                              File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute       self.error_handler.check_response(response)                                                                           File "/app/.heroku/python/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response                                                                                                                     raise exception_class(message, screen, stacktrace)                                                                  selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process`

Any help please?

**Comment by pyronlaboratory** [comment]
@XtremePwnership

Error `invalid argument: can't kill an exited process` originates when the selenium is unable to spawn a new instance of the web driver. 

Incompatibility between Firefox and Geckodriver could be a probable reason as well. 

I've hardcoded the stable versions for Firefox and Geckodriver in the code. However, if those version doesn't seem to work out for you, feel free to fork the repo and update your codebase with desired versions for Firefox and Geckodriver.

**Comment by XtremePwnership** [comment]
Thank you.
