### ISSUE TITLE
failed to compile Firefox

### ISSUE THREAD

**Issue by kunalkumar007** [pyronlaboratory/heroku-integrated-firefox-geckodriver#19]
I just used this repo to install firefox and geckodriver but getting this error and I know little about heroku and scripts . Hope this helps.

`Installing requirements with pip
-----> Firefox
geckodriver app detected
/tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/bin/compile: line 16: cd: /tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/fonts: No such file or directory
/tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/bin/compile: line 82: syntax error near unexpected token `;'
 !     Push rejected, failed to compile Firefox
geckodriver app.
 !     Push failed`

**Comment by dedobbin** [comment]
Pretty much same situation here

-----> Firefox

```
geckodriver app detected

/tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/bin/compile: line 16: cd: /tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/fonts: No such file or directory

/tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/bin/compile: line 82: syntax error near unexpected token `;'
```

**Comment by mwitek** [comment]
When will this be fixed?
