### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by QairexStudio** [pyronlaboratory/heroku-integrated-firefox-geckodriver#21]
geckodriver app detected
/tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/bin/compile: line 16: cd: /tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/fonts: No such file or directory
/tmp/codon/tmp/buildpacks/768374e866288447126d1d75779462919bfbaab4/bin/compile: line 82: syntax error near unexpected token `;'
 !     Push rejected, failed to compile Firefox
geckodriver app.
 !     Push failed

**Comment by Chr1st1anG** [comment]
Add a ; to line 82.

**Comment by jacknugget** [comment]
anyone found a solution?
