### ISSUE TITLE
Couldn't load XPCOM

### ISSUE THREAD

**Issue by aperezmontan** [pyronlaboratory/heroku-integrated-firefox-geckodriver#6]
Thanks for the buildpack 😃 

I'm getting this error when trying to start a new instance of Selenium Webdriver:

```
XPCOMGlueLoad error for file /app/vendor/firefox/libxul.so:
libXt.so.6: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

Any ideas ?  I've set all the environment variables in the README.  Here's my configuration :

```
Selenium::WebDriver::Firefox::Binary.path = ENV['FIREFOX_BIN']
Selenium::WebDriver::Firefox.driver_path = ENV['GECKODRIVER_PATH']
Selenium::WebDriver.logger.level = :debug
```

Thanks !

**Comment by pyronlaboratory** [comment]
The reported error is not confined to this build pack; evident from the fact that you were able to deploy the application.

Hence I'm not sure if I can help you here.

An **XPCOM** related error usually roots back to improper usage of firefox libraries.

A runtime error while creating the *web driver* instance, suggests that the application code is probably creating a troubling subroutine of some sort. I can help you debug if you can share some logs and relevant application code snippets.

**Comment by bawat** [comment]
I am also experiencing this problem. No problems with Chrome.
![image](https://user-images.githubusercontent.com/6385212/75834200-47010600-5db3-11ea-82c0-67a297de7ba1.png)
`
System.setProperty("webdriver.gecko.driver", System.getenv("FIREFOX_BIN"));
WebDriver driver = new FirefoxDriver();`

**Comment by mohitsahoo** [comment]
Has anybody found any fixes?

**Comment by pyronlaboratory** [comment]
This issue has been closed because there has been no response from the original author. 

@bawat, I'd suggest you open a new issue to follow up if you're still struggling with the setup.
